name: Python CI-CD Automation Practice

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check Syntax
        run: python -m py_compile app.py

      - name: Run App with Secrets
        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}
        run: python app.py